#!/bin/bash
. _env
source "${CONFIG_ROOT}/.ambient"
CACHE="${CACHE_ROOT}/.ambient"

function getLatestConditions() {
    if checkCache $CACHE 300; then
        echo $(cat $CACHE)
        return
    fi

    local DATA=$(curl -s "https://rt.ambientweather.net/v1/devices?applicationKey=${AMBIENT_APPLICATION_KEY}&apiKey=${AMBIENT_API_KEY}")
    echo $DATA > $CACHE
    echo $DATA
}

getLatestConditions