#!/bin/bash

setWallpaper(){
  local SAVE_DIR="/tmp/bingpaper";
  mkdir -p $SAVE_DIR;
  rm -rf "$SAVE_DIR/*";

  echo "=== BingPaper starting at $(date) ===";
  echo " Save path : $SAVE_DIR";
  local IMAGE_DATA=$(curl -s https://www.bing.com/HPImageArchive.aspx\?format\=js\&n\=1 | jq '.images[0].urlbase' -r);

  echo " Building URL to fetch...";
  echo "  Orig : $IMAGE_DATA";

  local PATHNAME="${IMAGE_DATA}_UHD.jpg";
  local URL="https://www.bing.com$PATHNAME";
  local IFS='='; read P1 P2 <<< "${PATHNAME}";
  local FINAL_PATH="$SAVE_DIR/$P2";

  echo "  URL  : $URL";
  echo "  File : $FINAL_PATH";

  curl -s --output "${FINAL_PATH}" "${URL}";
  echo " Setting wallpaper to $FINAL_PATH"
  osascript -e 'tell application "System Events"' -e 'tell every desktop' -e "set picture to \"$FINAL_PATH\"" -e 'end' -e 'end'
  echo "=== BingPaper finished at $(date) ==="
}

setWallpaper