#!/bin/bash
# for interacting with rooter
. _env
source "${CONFIG_ROOT}/.rooter"
COOKIE_JAR="${CACHE_ROOT}/.router-auth.txt"
COOKIE_JAR_EXPIRATION_TIME=600
DEFAULT_CACHE_EXPIRATION_TIME=600

function translateBandwidth() {
    case $(($1)) in
    0) echo 5 ;;
    1) echo 10 ;;
    2) echo 15 ;;
    3) echo 20 ;;
    4) echo 25 ;;
    5) echo 30 ;;
    6) echo 40 ;;
    7) echo 50 ;;
    8) echo 60 ;;
    9) echo 70 ;;
    10) echo 80 ;;
    11) echo 90 ;;
    12) echo 100 ;;
    13) echo 200 ;;
    14) echo 400 ;;
    esac
}

function login() {
    if checkCache $COOKIE_JAR $COOKIE_JAR_EXPIRATION_TIME; then
        return
    fi
    curl -s $ROUTER_ENDPOINT -X POST --data-urlencode 'luci_username=root' --data-urlencode "luci_password=${ROUTER_PASSWORD}" --cookie-jar $COOKIE_JAR
}

# cell status
# /cgi-bin/luci/admin/modem/get_csq'

function getStatus() {
    local DATA=$(curl -s "$ROUTER_ENDPOINT/admin/modem/get_csq" --cookie $COOKIE_JAR)
}

# AT debug log
# /cgi-bin/luci/admin/modem/get_atlog

function getAtDebugLog() { return; }

function getServingCell() {
    local DATA=$(submitCommand "${CACHE_ROOT}/.gateway_status" 300 at+qeng=\"servingcell\")
    local RESULT=$(echo $DATA | jq -r .result | tr -d ' ')
    # echo $RESULT
    local arrIN=(${RESULT//,/ })

    local MODE=$(echo $RESULT | cut -d',' -f3)
    local BAND=$(echo $RESULT | cut -d',' -f11)
    local BANDWIDTH=$(translateBandwidth $(echo $RESULT | cut -d',' -f12))
    local RSRP=$(echo $RESULT | cut -d',' -f13)
    local RSRQ=$(echo $RESULT | cut -d',' -f14)
    local SINR=$(echo $RESULT | cut -d',' -f15)

    # echo $MODE $BAND $BANDWIDTH $RSRP $RSRQ $SINR

    jq -n --argjson mode "$MODE" \
        --argjson band "$BAND" \
        --argjson bandwidth "$BANDWIDTH" \
        --argjson rsrp "$RSRP" \
        --argjson rsrq "$RSRQ" \
        --argjson sinr "$SINR" \
        '{"mode":$mode,"band":$band,"bandwidth":$bandwidth,"rsrp":$rsrp,"rsrq":$rsrq,"sinr":$sinr}'
}

# submit AT command
function getCAStatus() {
    local DATA=$(submitCommand "${CACHE_ROOT}/.gateway_qcainfo" $DEFAULT_CACHE_EXPIRATION_TIME AT+qcainfo)
    local RESULT=$(echo $DATA | jq -r .result | tr -d '\n' | tr -d '\r' | tr -d ': ')
    local lines=(${RESULT//+/ })

    for i in "${lines[@]}"; do
        if [[ "$i" == *"PCC"* ]]; then
            local PRIMARY=$(echo $i | cut -d',' -f4)
            local PRIMARY_BANDWIDTH_SIZE=$(translateBandwidth $(echo $i | cut -d',' -f3))
            local PRIMARY_BAND=$(echo $i | cut -d',' -f5)
        fi
        if [[ "$i" == *"SCC"* ]]; then
            local SECONDARY=$(echo $i | cut -d',' -f4)
            local SECONDARY_BANDWIDTH_SIZE=$(translateBandwidth $(echo $i | cut -d',' -f3))
            # modem response is weird, doesn't match the docs - so secondary band isnt working
            local SECONDARY_BAND=$(echo $i | cut -d',' -f5)
            if [[ "$SECONDARY_BAND" == 1 ]]; then
                # forgive me
                local SECONDARY_BAND=$(echo $SECONDARY | cut -d 'D' -f2 | cut -d '"' -f1)
            fi
        fi
    done

    # echo $PRIMARY $PRIMARY_BANDWIDTH_SIZE $PRIMARY_BAND $SECONDARY $SECONDARY_BANDWIDTH_SIZE $SECONDARY_BAND

    jq -n --argjson primary "$PRIMARY" \
        --argjson primary_bandwidth_size "$PRIMARY_BANDWIDTH_SIZE" \
        --argjson primary_band "$PRIMARY_BAND" \
        --argjson secondary "$SECONDARY" \
        --argjson secondary_bandwidth_size "$SECONDARY_BANDWIDTH_SIZE" \
        --argjson secondary_band "$SECONDARY_BAND" \
        '{"carriers":[{"primary":$primary,"bandwidth":$primary_bandwidth_size,"band":$primary_band},{"secondary":$secondary,"bandwidth":$secondary_bandwidth_size,"band":$secondary_band}]}'
}

function getTemperature() {
    local DATA=$(submitCommand "${CACHE_ROOT}/.gateway_temperature" $DEFAULT_CACHE_EXPIRATION_TIME AT+QTEMP)
    local RESULT=$(echo $DATA | jq -r .result | tr -d '\n' | tr -d '\r')
    local lines=(${RESULT//+/ })

    for i in "${lines[@]}"; do
        if [[ "$i" == *"QTEMP:"* ]]; then
            local LINE=$(echo $i | cut -d':' -f2)
            local ITEM=$(echo $LINE | cut -d',' -f1)
            local TEMPERATURE=$(echo $LINE | cut -d',' -f2)
            if [[ "$TEMPERATURE" == *"0"* ]]; then
                continue # skip 0s
            fi
            local DATA=$(jq -n --argjson item "$ITEM" --argjson temperature "$TEMPERATURE" '{($item): $temperature | tonumber}')
            echo $DATA
        fi
    done | jq -n '[inputs] | add'
}

# /cgi-bin/luci/admin/modem/get_csq

function getDashboard() {
    local DATA=$(submitCommand "${CACHE_ROOT}/.gateway_dashboard" 60)
    echo $DATA | jq -r .result
}

function submitCommand() { # cache, cachetime, param1, param2
    if checkCache $1 $2; then
        echo $(cat $1)
        return
    fi

    # /cgi-bin/luci/admin/modem/send_atcmd?set=at%2Bqcainfo
    local DATA=$(curl --get --silent --data-urlencode "set=$3" "${ROUTER_ENDPOINT}admin/modem/send_atcmd" -b $COOKIE_JAR)
    echo $DATA >$1
    echo $DATA
}

function assembleStandardOut() {
    local SERVING_CELL=$(getServingCell)
    local CA_STATUS=$(getCAStatus)
    local TEMPERATURE=$(getTemperature)
    local TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

    jq -n --argjson serving "$SERVING_CELL" \
        --argjson castatus "$CA_STATUS" \
        --arg timestamp "$TIMESTAMP" \
        --argjson temperature "$TEMPERATURE" \
        '{"timestamp":$timestamp,"temp":$temperature,"servingCell":$serving,"ca":$castatus}'
}

function resetUsb() {
    ssh tmo 'usbreset 2c7c:0801'
}

function rebootAll() {
    resetUsb
    sleep 1
    ssh tmo 'reboot'
}

function resetModem() {
    sendCommand "${CACHE_ROOT}/.gateway_cfun" 0 "AT+CFUN=1,1"
}

login
if [[ -n $1 ]]; then
    #echo "executing $1"
    if [[ "$1" == "reboot" ]]; then
        echo "Resetting modem & rebooting router"
        rebootAll
        exit 0
    fi
    if [[ "$1" == "reset" ]]; then
        echo "Resetting modem via CFUN"
        resetModem
        exit 0
    fi
    if [[ "$1" == "resetusb" ]]; then
        echo "Resetting modem USB"
        resetUsb
        exit 0
    fi
    submitCommand "${CACHE_ROOT}/.gateway_${1}" 600 $1
    if [[ -n $2 ]]; then
        echo $(cat "${CACHE_ROOT}/.gateway_${1}")
    else
        cat "${CACHE_ROOT}/.gateway_${1}" | jq -r .result
    fi
else
    assembleStandardOut
fi

# {"result":"AT+qtemp\n+QTEMP:\"modem-lte-sub6-pa1\",\"30\"\n+QTEMP:\"modem-sdr0-pa0\",\"0\"\n+QTEMP:\"modem-sdr0-pa1\",\"0\"\n+QTEMP:\"modem-sdr0-pa2\",\"0\"\n+QTEMP:\"modem-sdr1-pa0\",\"0\"\n+QTEMP:\"modem-sdr1-pa1\",\"0\"\n+QTEMP:\"modem-sdr1-pa2\",\"0\"\n+QTEMP:\"modem-mmw0\",\"0\"\n+QTEMP:\"aoss-0-usr\",\"33\"\n+QTEMP:\"cpuss-0-usr\",\"33\"\n+QTEMP:\"mdmq6-0-usr\",\"33\"\n+QTEMP:\"mdmss-0-usr\",\"33\"\n+QTEMP:\"mdmss-1-usr\",\"33\"\n+QTEMP:\"mdmss-2-usr\",\"33\"\n+QTEMP:\"mdmss-3-usr\",\"32\"\n+QTEMP:\"modem-lte-sub6-pa2\",\"30\"\n+QTEMP:\"modem-ambient-usr\",\"31\"\n\nOK\n"}
# AT+qtemp
# +QTEMP:"modem-lte-sub6-pa1","30"
# +QTEMP:"modem-sdr0-pa0","0"
# +QTEMP:"modem-sdr0-pa1","0"
# +QTEMP:"modem-sdr0-pa2","0"
# +QTEMP:"modem-sdr1-pa0","0"
# +QTEMP:"modem-sdr1-pa1","0"
# +QTEMP:"modem-sdr1-pa2","0"
# +QTEMP:"modem-mmw0","0"
# +QTEMP:"aoss-0-usr","33"
# +QTEMP:"cpuss-0-usr","33"
# +QTEMP:"mdmq6-0-usr","33"
# +QTEMP:"mdmss-0-usr","33"
# +QTEMP:"mdmss-1-usr","33"
# +QTEMP:"mdmss-2-usr","33"
# +QTEMP:"mdmss-3-usr","32"
# +QTEMP:"modem-lte-sub6-pa2","30"
# +QTEMP:"modem-ambient-usr","31"

# OK

# +QENG: "servingcell","NOCONN","NR5G-SA","TDD",310,260,xxxxxxx,41,xxxxxx,509790,41,10,-83,-11,23,1,-
# "servingcell","NOCONN","NR5G-SA","TDD",        310,  260,  xxxxxxx ,41,    xxxxxx, 524190, 41,    10,               -81,   -11,   24,    1     -
# ""+QENG:               "LTE",    <duplex_mode>,<MCC>,<MNC>,<cellID>,<PCID>,<TAC> , <ARFCN>,<band>,<NR_DL_bandwidth>,<RSRP>,<RSRQ>,<SINR>,<scs>,<sxrlev>
#
# +QCAINFO: "PCC",xxxxxx,10,"NR5G BAND 41",41
# +QCAINFO: "SCC",xxxxxx,1,"NR5G BAND 71",1,191,0,-,-

#+QCAINFO: "PCC",<freq>,<bandwidth>,<band>,<pcell_state>,<PCID>,<RSRP>,<RSRQ>,<RSSI>,<SINR>
#+QCAINFO: "SCC",<freq>,<bandwidth>,<band>,<scell_state>,<PCID>,<RSRP>,<RSRQ>,<RSSI>,<SINR> */
